import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "docs/reference/api/brabo-api",
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/jwks-controller-jwks",
          label: "Chaves públicas de verificação do access token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-login",
          label: "Autentica e emite o par access + refresh",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-logout",
          label: "Revoga a família do refresh apresentado",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-oauth-callback",
          label: "Recebe o retorno do OAuth de login social",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-oauth-start",
          label: "Redireciona para o provider OAuth para login social",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-refresh",
          label: "Rotaciona o refresh e emite um par novo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-register",
          label: "Cria uma conta e envia o e-mail de verificação",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-request-password-reset",
          label: "Pede o link de redefinição de senha",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-reset-password",
          label: "Define a senha nova a partir do token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-verify-email",
          label: "Confirma o e-mail com o token de uso único",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "gates",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/gates-controller-listar",
          label: "O registro de gates ativos",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "git",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/git-controller-callback",
          label: "Recebe o retorno do OAuth e redireciona para a web",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-blame",
          label: "Anota cada linha de um arquivo com o commit que a tocou",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-branches",
          label: "Lista as branches com ahead/behind e a PR aberta associada",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-file",
          label: "Devolve o conteúdo de um arquivo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-pull-requests",
          label: "Lista as PRs/MRs do repositório",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-diff",
          label: "Devolve o diff de uma PR, normalizado por provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-search",
          label: "Busca texto no repositório, com orçamento",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-tree",
          label: "Lista UM nível da árvore do repositório",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-connect",
          label: "Começa o OAuth com o provider de git",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-provision",
          label: "Cria o repositório e dispara o bootstrap de Gitflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-adopt",
          label: "Adota um repositório que já existe, sem criar nada",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-get-bootstrap",
          label: "Devolve o estado do bootstrap de Gitflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-reconhecer-falha-de-protecao",
          label: "Reconhece a falha ao proteger as branches e segue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-plan",
          label: "Devolve o plano de bootstrap e o que foi decidido sobre ele",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-approve-plan",
          label: "Aprova o plano INTEIRO e roda o bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-skip-plan",
          label: "Adota o repositório COMO ESTÁ, dispensando o bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-get",
          label: "Devolve o repositório provisionado do projeto",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "infraestrutura",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/health-controller-check",
          label: "Readiness — o processo consegue atender de verdade",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/health-controller-live",
          label: "Liveness — o processo ainda atende requisição",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/metrics-controller-scrape",
          label: "Expõe as métricas no formato de exposição do Prometheus",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "internal",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/internal-gates-controller-ler",
          label: "Lê o registro declarativo de gates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-models-controller-sync",
          label: "Sincroniza o catálogo de modelos de todos os providers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-backlog",
          label: "O backlog do projeto em árvore, para o PO ler o que já escreveu",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-business-rules",
          label: "As regras de negócio do projeto, com cobertura, para o PO ler",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-git-remote",
          label: "O remoto de trabalho do projeto, para buscar e empurrar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-product-metrics",
          label: "O funil de entrega e DORA parcial do projeto, para o PO ler",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-create-action",
          label: "Propõe uma ação com efeito externo em nome de um agente",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-anamnese-context",
          label: "Monta o contexto de uma rodada da Anamnese",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-c-4-diagram",
          label: "Gera uma versão nova do diagrama C4 (Context + Container)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-record-delegation-outcome",
          label: "Registra o desfecho de uma delegação de área",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-dev-context",
          label: "Monta o contexto completo de uma tarefa para o dev agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-epic",
          label: "Cria um épico do backlog",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-list-events",
          label: "Pagina o event log da sessão para o engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-append-event",
          label: "Anexa um evento ao log da sessão, em nome de um agente",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-gate-verdict",
          label: "Registra o parecer de QA ou SecOps sobre a PR de uma tarefa",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-handoff",
          label: "Oferece um handoff de um agente para outro",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-hypotheses",
          label: "Registra uma rodada de análise e as hipóteses dela",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-pr-files",
          label: "Devolve os arquivos de uma PR de infra para os gates lerem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-context",
          label: "Monta o contexto inicial do InfraAgent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-gate-verdict",
          label: "Registra o parecer de QA ou SecOps sobre uma PR de infra",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-instruction-patch",
          label: "Propõe um patch no arquivo de instrução de um agente",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-llm-turn",
          label: "Executa um turno de LLM medido, com suporte a ferramentas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-llm-turn-stream",
          label: "Executa um turno de LLM com a resposta em stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-max-parallel-proposal",
          label: "Propõe subir o teto de paralelismo de uma área",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-module-map",
          label: "Publica uma versão nova do module_map",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-pending-work",
          label: "A sessão tem trabalho pendente que impede encerrá-la?",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-proficiency",
          label: "Grava os perfis de proficiência derivados na rodada",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-project-image",
          label: "Fixa a imagem de container do projeto",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-psychologist-context",
          label: "Monta o contexto de uma rodada do Psicólogo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-story",
          label: "Cria uma história com RF, RNF, DoD, DoR e regras cobertas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-story-modules",
          label: "Associa uma história aos módulos que ela toca",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-task",
          label: "Cria uma tarefa dentro de uma história",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-block-task",
          label: "Marca a tarefa como bloqueada, com o motivo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-open-gate-endpoint",
          label: "Abre a esteira de gates da tarefa, começando pelo QA",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-mark-task-status",
          label: "Move a tarefa de estado ao longo do trabalho",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-claim-task",
          label: "Reivindica atomicamente a próxima tarefa pegável do módulo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-report",
          label: "Reporta que o processo da sessão terminou no engine",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "projetos",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-get",
          label: "Devolve um projeto pelo id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-update",
          label: "Altera nome ou slug do projeto",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-remove",
          label: "Remove o projeto",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/containers-controller-estado",
          label: "Estado do container do projeto (a decisão de imagem vigente)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/containers-controller-ciclo-de-vida",
          label: "Ciclo de vida do container do projeto (estado registrado)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-list-members",
          label: "Lista os membros do projeto com o papel efetivo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-add-member",
          label: "Associa um usuário ao projeto",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-remove-member",
          label: "Desassocia um usuário do projeto",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-get-permissions",
          label: "Lê o permissions.json do projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-set-permissions",
          label: "Reescreve o permissions.json do projeto",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "execução",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-list-areas",
          label: "As áreas de agente do projeto, com o teto de cada lead",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-set-max-parallel",
          label: "Muda o teto de paralelismo de uma área",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-activate",
          label: "Ativa a fase de execução e sobe um dev agent por módulo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-get-session",
          label: "Devolve a sessão de execução vigente do projeto, ou nada",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-rearm",
          label: "Rearma um dev agent travado pelo circuit breaker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-parallelize",
          label: "Pede mais um dev agent para um módulo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-unblock",
          label: "Destrava uma tarefa bloqueada",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ações",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/agent-autonomy-controller-list",
          label: "Lista a autonomia concedida a cada agente",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/agent-autonomy-controller-set",
          label: "Define a autonomia de um agente para um tipo de ação",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-list",
          label: "Pagina as ações propostas na sessão",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-propose",
          label: "Propõe uma ação com efeito externo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-approve",
          label: "Aprova a ação, uma vez",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-approve-always",
          label: "Aprova a ação e grava o padrão no permissions.json",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-deny",
          label: "Recusa a ação",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "llm",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-agent-binding",
          label: "Resolve qual modelo um agente usa, e de onde ele veio",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-agent-binding",
          label: "Fixa o modelo de um agente NESTE projeto",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-clear-agent-binding",
          label: "Faz o agente voltar a herdar o modelo da área",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-project-agent-costs",
          label: "Quebra o gasto do projeto por agente, nos últimos 30 dias",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-area-binding",
          label: "Resolve qual modelo é o padrão de uma área, e de onde ele veio",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-area-binding",
          label: "Define o modelo padrão de uma área",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-clear-area-binding",
          label: "Faz a área voltar a herdar o modelo do projeto",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-project-budget",
          label: "Lê o orçamento do projeto e o quanto já foi gasto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-set-project-budget",
          label: "Define o teto de gasto do projeto",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-project-binding",
          label: "Lê o binding de modelo do projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-project-binding",
          label: "Define o modelo do projeto",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-list",
          label: "Lista os modelos ativos NO WORKSPACE do projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-session-budget",
          label: "Lê o orçamento da sessão e o gasto acumulado",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-set-session-budget",
          label: "Define o teto de gasto da sessão",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/chat-controller-chat",
          label: "Conversa com o modelo da sessão, com a resposta em stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-session-binding",
          label: "Resolve qual modelo a sessão usa, e de onde ele veio",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-session-binding",
          label: "Fixa o modelo desta sessão",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-session-token-usage",
          label: "Quebra o gasto da sessão por agente",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/spend-controller-get-my-spend",
          label: "O meu consumo neste projeto, por sessão e por dia",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-credential-spend",
          label: "Quanto as chaves do owner gastaram, por provider e por mês",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-workspace-binding",
          label: "Lê o binding de modelo do workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-workspace-binding",
          label: "Define o modelo default do workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-price-changes",
          label: "Histórico de mudanças de preço de um modelo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-update-pricing",
          label: "Corrige o preço de um modelo",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-activate",
          label: "Liga ou desliga modelos no seletor (lote)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-catalog",
          label: "Lista o catálogo INTEIRO, inclusive inativo e indisponível",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-sync",
          label: "Força agora o sync de catálogo que o job periódico faz",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-uses",
          label: "Marca para que o workspace usa cada modelo (lote)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/spend-controller-get-workspace-spend-report",
          label: "Quebra o gasto do workspace por modelo, provider, projeto, ator e dia",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "anamnese",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-versions",
          label: "Lista as versões de instrução de um agente",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-rollback-version",
          label: "Restaura uma versão anterior da instrução de um agente",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-run",
          label: "Roda a Anamnese agora, sem esperar o tick",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-event",
          label: "Devolve um evento do projeto pelo id, resolvendo a sessão",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-all-versions",
          label: "Lista o histórico de instruções de todos os agentes do projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-proficiency",
          label: "Devolve o perfil de proficiência",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-delete-mine",
          label: "Apaga o próprio perfil e registra o opt-out",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-opt-in-mine",
          label: "Volta a permitir o perfilamento do próprio usuário",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "backlog",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-architecture",
          label: "Devolve o module_map vigente, as ADRs e as pendências",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-backlog",
          label: "Devolve a árvore épico → história → tarefa",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-coverage",
          label: "Calcula a cobertura regra de negócio → histórias",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-infra-artifacts",
          label: "Lista as PRs de infra e o estágio de gate de cada uma",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-return",
          label: "Devolve ao PO uma história recusada, com o motivo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-promote",
          label: "Promove a `ready` as histórias que o PO propôs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "psicólogo",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-hypotheses",
          label: "Lista as hipóteses do Psicólogo sobre os agentes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-accept",
          label: "Aceita uma hipótese",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-dismiss",
          label: "Descarta uma hipótese",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-analyses",
          label: "Lista as rodadas de análise com tier e custo real",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-reanalyze",
          label: "Dispara uma reanálise da sessão",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "rag",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-obter-cobertura",
          label: "Cobertura do índice: arquivos/sessões indexados contra o total real",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-reindexar",
          label: "Reindexa docs/ADR/sessões do projeto (full rebuild idempotente)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-buscar",
          label: "Busca híbrida (vetor + léxico) nos chunks indexados do projeto",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sessões",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-list",
          label: "Lista as sessões do projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-create",
          label: "Abre uma sessão no projeto",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-get",
          label: "Devolve uma sessão pelo id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-rename",
          label: "Dá ou tira o nome amigável da sessão",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-list-events",
          label: "Pagina o event log da sessão",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-append-event",
          label: "Anexa um evento ao log da sessão",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-get-event",
          label: "Devolve um evento do log pelo id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-issue-socket-ticket",
          label: "Emite um ticket opaco de uso único para o socket da sessão",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-transition",
          label: "Move a sessão para outro estado",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "agentes",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-cancel",
          label: "Cancela o turno em curso do agente ativo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-message",
          label: "Envia uma mensagem ao agente ativo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-start",
          label: "Sobe um agente na sessão",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-submit-structured-question-answer",
          label: "Responde a um conjunto de perguntas estruturadas do agente",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-handoff-infra",
          label: "Confirma que a arquitetura está pronta e oferece o handoff ao Infra",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-validate-necessity-handoff",
          label: "Confirma que a necessidade de negócio do Criativo foi validada",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-handoffs",
          label: "Lista os handoffs entre agentes da sessão",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-accept",
          label: "Aceita um handoff e ativa o agente de destino",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-readiness",
          label: "Confirma que o levantamento com o Criativo terminou",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "credenciais",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-list",
          label: "Lista as credenciais do próprio usuário",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-create",
          label: "Registra ou substitui a chave de API de um provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-remove",
          label: "Remove a credencial de um provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-test",
          label: "Verifica a credencial JÁ gravada contra o provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-credentials-controller-create",
          label: "Registra um token de git (cifrado, sem testar)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "workspaces",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-list",
          label: "Lista os workspaces de quem chamou",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-create",
          label: "Cria um workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get",
          label: "Devolve um workspace pelo id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-update",
          label: "Altera nome ou slug do workspace",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-remove",
          label: "Remove o workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-add-member",
          label: "Associa um usuário ao workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-list-projects",
          label: "Lista os projetos do workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-create-project-in-workspace",
          label: "Cria um projeto dentro do workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-projects-status",
          label: "Contagem de tasks bloqueadas por projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-projects-summary",
          label: "Tudo que os cards do dashboard desenham, numa chamada",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-summary",
          label: "Resumo agregado do workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-unread-events",
          label: "Os eventos não lidos de vários projetos, numa chamada",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
