import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "docs/reference/api/brabo-api",
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/jwks-controller-jwks",
          label: "Public access token verification keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-login",
          label: "Authenticates and issues the access + refresh pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-logout",
          label: "Revokes the family of the presented refresh",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-oauth-callback",
          label: "Receives the social login OAuth callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-oauth-start",
          label: "Redirects to the OAuth provider for social login",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-refresh",
          label: "Rotates the refresh and issues a new pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-register",
          label: "Creates an account and sends the verification email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-request-password-reset",
          label: "Requests the password reset link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-reset-password",
          label: "Sets the new password from the token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/auth-controller-verify-email",
          label: "Confirms the email with the single-use token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "gates",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/gates-controller-listar",
          label: "The registry of active gates",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "git",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/git-controller-callback",
          label: "Receives the OAuth return and redirects to the web app",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-blame",
          label: "Annotates every line of a file with the commit that touched it",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-branches",
          label: "Lists branches with ahead/behind and the associated open PR",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-file",
          label: "Returns a file's content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-pull-requests",
          label: "Lists the repository's PRs/MRs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-diff",
          label: "Returns the diff of a PR, normalized across providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-search",
          label: "Searches text in the repository, with a budget",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/code-controller-tree",
          label: "Lists ONE level of the repository tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-connect",
          label: "Starts OAuth with the git provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-provision",
          label: "Creates the repository and triggers the Gitflow bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-adopt",
          label: "Adopts an existing repository, without creating anything",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-get-bootstrap",
          label: "Returns the Gitflow bootstrap state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-reconhecer-falha-de-protecao",
          label: "Acknowledges the branch-protection failure and moves on",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-plan",
          label: "Returns the bootstrap plan and what was decided about it",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-approve-plan",
          label: "Approves the WHOLE plan and runs the bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-skip-plan",
          label: "Adopts the repository AS IS, dismissing the bootstrap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-controller-get",
          label: "Returns the project's provisioned repository",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "infrastructure",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/health-controller-check",
          label: "Readiness — the process can actually serve traffic",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/health-controller-live",
          label: "Liveness — the process still serves requests",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/metrics-controller-scrape",
          label: "Exposes metrics in Prometheus exposition format",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "internal",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/internal-gates-controller-ler",
          label: "Reads the declarative gate registry",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-graph-controller-upsert",
          label: "Publishes a prompt template version, idempotent by hash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-graph-controller-get-by-name",
          label: "Looks up a prompt template by name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-models-controller-sync",
          label: "Syncs the model catalog across all providers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-backlog",
          label: "The project's backlog as a tree, for the PO to read what was already written",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-business-rules",
          label: "The project's business rules, with coverage, for the PO to read",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-git-remote",
          label: "The project's working remote, to fetch and push",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-product-metrics",
          label: "The project's delivery funnel and partial DORA metrics, for the PO to read",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-projects-controller-confirm-workspace-verification",
          label: "The runner confirms the path of a 'runner' project (RN-423)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-rag-controller-buscar",
          label: "Hybrid search over the project's RAG index, for the engine's tool",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-create-action",
          label: "Proposes an action with an external effect on behalf of an agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-anamnese-context",
          label: "Assembles the context for an Anamnesis round",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-c-4-diagram",
          label: "Generates a new version of the C4 diagram (Context + Container)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-record-delegation-outcome",
          label: "Records the outcome of an area delegation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-dev-context",
          label: "Assembles the full context of a task for the dev agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-epic",
          label: "Creates a backlog epic",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-list-events",
          label: "Paginates the session's event log for the engine",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-append-event",
          label: "Appends an event to the session's log, on behalf of an agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-gate-verdict",
          label: "Records QA's or SecOps's verdict on a task's PR",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-handoff",
          label: "Offers a handoff from one agent to another",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-hypotheses",
          label: "Records an analysis round and its hypotheses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-pr-files",
          label: "Returns the files of an infra PR for the gates to read",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-context",
          label: "Assembles the InfraAgent's initial context",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-infra-gate-verdict",
          label: "Records QA's or SecOps's verdict on an infra PR",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-instruction-patch",
          label: "Proposes a patch to an agent's instruction file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-llm-turn",
          label: "Runs a metered LLM turn, with tool support",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-llm-turn-stream",
          label: "Runs an LLM turn with the response streamed",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-max-parallel-proposal",
          label: "Proposes raising an area's parallelism cap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-module-map",
          label: "Publishes a new version of the module_map",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-pending-work",
          label: "Does the session have pending work that blocks closing it?",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-proficiency",
          label: "Records the proficiency profiles derived in the round",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-project-image",
          label: "Sets the project's container image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-psychologist-context",
          label: "Assembles the context for a Psychologist round",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-story",
          label: "Creates a story with functional/non-functional requirements, DoD, DoR, and covered rules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-story-modules",
          label: "Associates a story with the modules it touches",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-task",
          label: "Creates a task inside a story",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-block-task",
          label: "Marks the task as blocked, with the reason",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-open-gate-endpoint",
          label: "Opens the task's gate pipeline, starting with QA",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-mark-task-status",
          label: "Moves the task's state as work progresses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-claim-task",
          label: "Atomically claims the module's next claimable task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/internal-sessions-controller-report",
          label: "Reports that the session process terminated in the engine",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "projects",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-get",
          label: "Returns a project by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-update",
          label: "Changes the project's name or slug",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-remove",
          label: "Removes the project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/containers-controller-estado",
          label: "State of the project's container (the current image decision)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/containers-controller-ciclo-de-vida",
          label: "Lifecycle of the project's container (recorded state)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-convert-execution-mode-route",
          label: "Converts the project's execution mode",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-list-members",
          label: "Lists the project's members with their effective role",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-add-member",
          label: "Associates a user with the project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-remove-member",
          label: "Disassociates a user from the project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-get-permissions",
          label: "Reads the project's permissions.json",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/projects-controller-set-permissions",
          label: "Rewrites the project's permissions.json",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "actions",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/project-actions-controller-list",
          label: "Lists the PENDING actions of the whole project, across any session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/agent-autonomy-controller-list",
          label: "Lists the autonomy granted to each agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/agent-autonomy-controller-set",
          label: "Sets an agent's autonomy for an action type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-list",
          label: "Paginates the proposed actions in the session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-propose",
          label: "Proposes an action with external effect",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-approve",
          label: "Approves the action, once",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-approve-always",
          label: "Approves the action and records the pattern in permissions.json",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/actions-controller-deny",
          label: "Denies the action",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "execution",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-list-areas",
          label: "The project's agent areas, with each lead's cap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-set-budget",
          label: "Sets (or clears) an area's spend cap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-set-max-parallel",
          label: "Changes an area's parallelism cap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-activate",
          label: "Activates the execution phase and starts one dev agent per module",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-get-session",
          label: "Returns the project's current execution session, or nothing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-rearm",
          label: "Rearms a dev agent tripped by the circuit breaker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-parallelize",
          label: "Requests one more dev agent for a module",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/execution-controller-unblock",
          label: "Unblocks a blocked task",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "llm",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-agent-binding",
          label: "Resolves which model an agent uses, and where it came from",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-agent-binding",
          label: "Pins an agent's model in THIS project",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-clear-agent-binding",
          label: "Makes the agent go back to inheriting the area's model",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-project-agent-costs",
          label: "Breaks down the project spend by agent, over the last 30 days",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-area-binding",
          label: "Resolves what an area's default model is, and where it came from",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-area-binding",
          label: "Sets an area's default model",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-clear-area-binding",
          label: "Makes the area go back to inheriting the project's model",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-project-budget",
          label: "Reads the project budget and how much has already been spent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-set-project-budget",
          label: "Sets the project spend cap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-project-binding",
          label: "Reads the project model binding",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-project-binding",
          label: "Sets the project's model",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-list",
          label: "Lists the models active IN THE PROJECT's WORKSPACE",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-session-budget",
          label: "Reads the session budget and the accumulated spend",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-set-session-budget",
          label: "Sets the session spend cap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/chat-controller-chat",
          label: "Talks to the session's model, with the response streamed",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-session-binding",
          label: "Resolves which model the session uses, and where it came from",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-session-binding",
          label: "Pins the model for this session",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-session-token-usage",
          label: "Breaks down the session spend by agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/spend-controller-get-my-spend",
          label: "My own consumption in this project, by session and by day",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/budgets-controller-get-credential-spend",
          label: "How much the owner's keys spent, by provider and by month",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/hugging-face-models-controller-search",
          label: "Searches GGUF models on the Hugging Face Hub",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/hugging-face-models-controller-create-pull-request",
          label: "Creates a PENDING pull request — nothing downloads yet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/hugging-face-models-controller-get-status",
          label: "Status of a pull request, for the frontend to poll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/hugging-face-models-controller-confirm",
          label: "The second confirmation — actually runs the pull",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-get-workspace-binding",
          label: "Reads the workspace model binding",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/model-bindings-controller-set-workspace-binding",
          label: "Sets the default model for the workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-price-changes",
          label: "History of a model's price changes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-update-pricing",
          label: "Corrects a model's price",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-activate",
          label: "Turns models on or off in the selector (batch)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-catalog",
          label: "Lists the WHOLE catalog, including inactive and unavailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-sync",
          label: "Forces the catalog sync the periodic job does, right now",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/models-controller-uses",
          label: "Marks what the workspace uses each model for (batch)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/spend-controller-get-workspace-spend-report",
          label: "Breaks down the workspace's spend by model, provider, project, actor, and day",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "anamnesis",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-versions",
          label: "Lists an agent's instruction versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-rollback-version",
          label: "Restores a previous version of an agent's instruction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-run",
          label: "Runs the Anamnese now, without waiting for the tick",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-event",
          label: "Returns a project event by id, resolving its session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-all-versions",
          label: "Lists the instruction history of every agent in the project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-proficiency",
          label: "Returns the proficiency profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-delete-mine",
          label: "Deletes your own profile and records the opt-out",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/anamnese-controller-opt-in-mine",
          label: "Re-enables the user's own profiling",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "backlog",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-architecture",
          label: "Returns the current module_map, the ADRs, and the pending items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-backlog",
          label: "Returns the epic → story → task tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-coverage",
          label: "Computes business-rule → stories coverage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-infra-artifacts",
          label: "Lists infra PRs and the gate stage of each one",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-return",
          label: "Returns a refused story to the PO, with the reason",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/backlog-controller-promote",
          label: "Promotes stories the PO proposed to `ready`",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "psychologist",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-hypotheses",
          label: "Lists the Psychologist's hypotheses about the agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-accept",
          label: "Accepts a hypothesis",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-dismiss",
          label: "Dismisses a hypothesis",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-analyses",
          label: "Lists the analysis rounds with tier and real cost",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-status",
          label: "Reports whether the Psychologist can run a NEW analysis today",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/psychologist-controller-reanalyze",
          label: "Triggers a reanalysis of the session",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "projetos",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/personal-access-tokens-controller-list-pats",
          label: "Lista os próprios Personal Access Tokens deste projeto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/personal-access-tokens-controller-issue-pat",
          label: "Emite um Personal Access Token pro runner local",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/personal-access-tokens-controller-revoke-pat",
          label: "Revoga um Personal Access Token próprio",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/personal-access-tokens-controller-revoke-pat-as-maintainer",
          label: "Revoga o Personal Access Token de QUALQUER usuário no projeto",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/personal-access-tokens-controller-list-all-pats",
          label: "Lista TODOS os Personal Access Tokens do projeto, de qualquer usuário",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/runner-tickets-controller-runner-ticket",
          label: "Emite um ticket de uso único para o runner local conectar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/runner-tickets-controller-terminal-ticket",
          label: "Emite um ticket de uso único para a aba Terminal da web",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "rag",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-obter-cobertura",
          label: "Index coverage: indexed files/sessions against the real total",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-anexar-pasta-local",
          label: "Attaches a local folder (browser upload) as read-only reference (RN-455, ADR 0113)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-reindexar",
          label: "Reindexes the project's docs/ADR/sessions (idempotent full rebuild)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/rag-controller-buscar",
          label: "Hybrid search (vector + lexical) over the project's indexed chunks",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sessions",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-list",
          label: "Lists the project's sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-create",
          label: "Opens a session in the project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-get",
          label: "Returns a session by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-rename",
          label: "Sets or clears the session's friendly name",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-list-events",
          label: "Paginates the session's event log",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-append-event",
          label: "Appends an event to the session's log",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-get-event",
          label: "Returns a log event by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-issue-socket-ticket",
          label: "Issues an opaque, single-use ticket for the session's socket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/sessions-controller-transition",
          label: "Moves the session to another state",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "agents",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-cancel",
          label: "Cancels the active agent's turn in progress",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-message",
          label: "Sends a message to the active agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-start",
          label: "Starts an agent in the session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-submit-structured-question-answer",
          label: "Answers a set of the agent's structured questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-handoff-infra",
          label: "Confirms the architecture is ready and offers the handoff to Infra",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-validate-necessity-handoff",
          label: "Confirms the Criativo's business need has been validated",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-handoffs",
          label: "Lists the session's agent-to-agent handoffs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-request-manual",
          label: "Manually offers a handoff to a chosen agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-accept",
          label: "Accepts a handoff and activates the destination agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/agents-controller-readiness",
          label: "Confirms that the discovery session with the Criativo is done",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "credentials",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-list",
          label: "Lists the current user's own credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-create",
          label: "Registers or replaces a provider's API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-remove",
          label: "Removes a provider's credential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/credentials-controller-test",
          label: "Checks the ALREADY stored credential against the provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/git-credentials-controller-create",
          label: "Registers a git token (encrypted, without testing)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "users",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/user-preferences-controller-get",
          label: "Reads the authenticated user's language preference",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/user-preferences-controller-update",
          label: "Writes the authenticated user's language preference",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "workspaces",
      items: [
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-list",
          label: "Lists the caller's workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-create",
          label: "Creates a workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get",
          label: "Returns a workspace by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-update",
          label: "Changes the workspace's name or slug",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-remove",
          label: "Removes the workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-add-member",
          label: "Associates a user with the workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-list-projects",
          label: "Lists the workspace's projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-create-project-in-workspace",
          label: "Creates a project inside the workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-projects-status",
          label: "Count of blocked tasks per project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-projects-summary",
          label: "Everything the dashboard cards render, in one call",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-summary",
          label: "Aggregated workspace summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/reference/api/workspaces-controller-get-unread-events",
          label: "Unread events across multiple projects, in one call",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
