import Config

# Configure your database — mesmo Postgres/banco da api (DATABASE_URL
# compartilhada via docker-compose), separado apenas pelo schema "engine"
# (ver config/config.exs).
config :engine, Engine.Repo,
  url: System.get_env("DATABASE_URL", "ecto://brabo:brabo@localhost:5432/brabo"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :engine, EngineWeb.Endpoint,
  # {0, 0, 0, 0} para aceitar conexões de fora do container (docker-compose).
  # A porta em si é definida em config/runtime.exs (lido em todo ambiente).
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IcNS1hY4ajybc+mnu3gcKsjllky+qRuF+AxAw2OgHLSYszlxf1PITNnREBGsTeFI",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :engine, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Instrumentação ligada, exportação desligada (ADR 0035).
#
# Não há coletor em desenvolvimento, e o default do `otel_configuration` é um
# exportador OTLP para `localhost:4318` — ou seja, sem esta linha o engine gasta
# um batch condenado a cada ciclo. Com `:none`, o `otel_batch_processor` desabilita
# a tabela de export na inicialização e descarta a span no `on_end`, então a span
# continua sendo CRIADA (com `trace_id` real, que é o que correlaciona o log com
# a api) e só não sai do processo.
config :opentelemetry, traces_exporter: :none

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
