defmodule EngineWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :engine

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_engine_key",
    signing_salt: "tL6gc/L5",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  socket "/socket", EngineWeb.SessionSocket, websocket: true, longpoll: false

  # Runner local + terminal interativo (separado de "/socket" de propósito —
  # ver o moduledoc de EngineWeb.RunnerSocket): dois papéis SEM sessão de
  # chat associada, escopados por projeto.
  socket "/runner", EngineWeb.RunnerSocket, websocket: true, longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :engine,
    gzip: not code_reloading?,
    only: EngineWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :engine
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  # DEPOIS do RequestId, para a linha de acesso carregar o `request_id` na
  # metadata. Ver o moduledoc: filtra as rotas de probe, que o `Plug.Logger` não
  # filtraria.
  plug EngineWeb.Plugs.AccessLog

  # ANTES do router, porque preflight (`OPTIONS`) não casa rota nenhuma e morreria
  # com 404 dentro de um pipeline. Ele filtra por caminho — só as rotas de health,
  # nunca `/internal/*` nem `/metrics`. Ver o moduledoc (ADR 0037).
  #
  # Depois do `AccessLog` para o preflight aparecer no log como qualquer outra
  # requisição, e não desaparecer no meio do caminho.
  plug EngineWeb.Plugs.Cors

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EngineWeb.Router
end
