import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Escrito à mão, organizado por Diátaxis — tutorial, how-to, referência e
 * explicação não se misturam.
 *
 * Duas ausências deliberadas em relação ao molde completo do Diátaxis:
 *
 * - **how-to/** — não existe ainda. Um guia por tarefa real vale muito, mas
 *   criar arquivos finos só pra preencher a categoria é pior que não ter: o
 *   runbook já cobre as tarefas operacionais e o getting-started cobre o
 *   caminho de entrada.
 * Quando houver conteúdo genuíno, a categoria entra aqui — foi o que
 * aconteceu com **explanation/**, que nasceu com a página do mecanismo de
 * sincronização. Os 28 ADRs continuam sendo a maior parte da camada de
 * explicação deste projeto; `explanation/` é pra o que não é decisão datada.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '🚀 Comece aqui',
      collapsed: false,
      items: ['intro', 'getting-started'],
    },
    {
      type: 'category',
      label: '🏗️ Arquitetura',
      collapsed: false,
      items: [
        'architecture',
        {
          type: 'category',
          label: 'Decisões (ADR)',
          link: { type: 'doc', id: 'adr/adr-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'adr',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📐 Regras',
      collapsed: false,
      items: ['business-rules'],
    },
    {
      type: 'category',
      label: '📖 Referência',
      collapsed: false,
      items: [
        'reference/configuration',
        'reference/events',
        'reference/permissions',
        'reference/artifacts',
        'reference/git-providers',
        'reference/internal-api',
        'reference/scripts',
        'reference/rulesets',
        'security-surface',
      ],
    },
    {
      type: 'category',
      label: '💡 Explicação',
      collapsed: false,
      items: ['explanation/documentation-workflow', 'explanation/branching-policy'],
    },
    {
      type: 'category',
      label: '🛠️ Operação',
      collapsed: false,
      items: ['runbook'],
    },
    {
      type: 'category',
      label: '📚 Vocabulário',
      collapsed: false,
      items: ['glossary'],
    },
    {
      type: 'category',
      label: '🤝 Contribuir',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Como contribuir',
          href: 'https://github.com/daneiel/brabo/blob/dev/CONTRIBUTING.md',
        },
        {
          type: 'link',
          label: 'Onde pedir ajuda',
          href: 'https://github.com/daneiel/brabo/blob/dev/SUPPORT.md',
        },
        {
          type: 'link',
          label: 'Reportar vulnerabilidade',
          href: 'https://github.com/daneiel/brabo/blob/dev/SECURITY.md',
        },
      ],
    },
  ],
};

export default sidebars;
