import type {
  SidebarsConfig,
  SidebarItemConfig,
} from '@docusaurus/plugin-content-docs';
// O default export do arquivo gerado JÁ é o array de itens
// (`export default sidebar.apisidebar`), não um objeto de sidebars.
import apiSidebar from '../docs/reference/api/sidebar';

/**
 * A sidebar da referência de API, com os ids corrigidos.
 *
 * O `docusaurus-plugin-openapi-docs` deriva os ids do `outputDir` supondo que
 * ele esteja DENTRO do site. Aqui ele aponta para `../docs`, porque a fonte
 * única do Markdown é `docs/` na raiz — e o plugin acaba emitindo
 * `docs/reference/api/x` onde o id de verdade é `reference/api/x`.
 *
 * A correção mora aqui, e não numa reescrita do arquivo gerado, por dois
 * motivos: arquivo gerado se reescreve sozinho na próxima geração, e o
 * `docs:check` compara o hash dele com o que o plugin produz — mutá-lo faria
 * o check acusar deriva a cada rodada.
 */
function corrigirIds(itens: SidebarItemConfig[]): SidebarItemConfig[] {
  return itens.map((item) => {
    if (typeof item === 'string') return item.replace(/^docs\//, '');
    if (item.type === 'doc') {
      return { ...item, id: item.id.replace(/^docs\//, '') };
    }
    if (item.type === 'category') {
      return { ...item, items: corrigirIds(item.items) };
    }
    return item;
  });
}

/**
 * Escrito à mão, organizado por Diátaxis — tutorial, how-to, referência e
 * explicação não se misturam.
 *
 * Duas ausências deliberadas em relação ao molde completo do Diátaxis:
 *
 * - **how-to/** — não existe ainda. Um guia por tarefa real vale muito, mas
 *   criar arquivos finos só pra preencher a categoria é pior que não ter: o
 *   runbook já cobre as tarefas operacionais e o getting-started cobre o
 *   caminho de entrada.
 * Quando houver conteúdo genuíno, a categoria entra aqui — foi o que
 * aconteceu com **explanation/**, que nasceu com a página do mecanismo de
 * sincronização. Os 28 ADRs continuam sendo a maior parte da camada de
 * explicação deste projeto; `explanation/` é pra o que não é decisão datada.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '🚀 Comece aqui',
      collapsed: false,
      items: ['intro', 'getting-started'],
    },
    {
      type: 'category',
      label: '🏗️ Arquitetura',
      collapsed: false,
      items: [
        'architecture',
        {
          type: 'category',
          label: 'Decisões (ADR)',
          link: { type: 'doc', id: 'adr/adr-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'adr',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📐 Regras',
      collapsed: false,
      items: ['business-rules'],
    },
    {
      type: 'category',
      label: '📖 Referência',
      collapsed: false,
      items: [
        'reference/configuration',
        'reference/events',
        'reference/permissions',
        'reference/artifacts',
        'reference/git-providers',
        'reference/internal-api',
        'reference/scripts',
        'reference/rulesets',
        'security-surface',
        {
          type: 'category',
          label: 'Referência da API',
          collapsed: true,
          // Gerada do OpenAPI por `pnpm docs:generate` — uma página por rota,
          // agrupadas por tag. Nunca editada à mão.
          items: corrigirIds(apiSidebar as SidebarItemConfig[]),
        },
      ],
    },
    {
      type: 'category',
      label: '💡 Explicação',
      collapsed: false,
      items: [
        'explanation/documentation-workflow',
        'explanation/branching-policy',
        'explanation/observability',
        'explanation/primeiro-dogfooding',
        'explanation/execucao-real-hello-world',
        'explanation/achados-execucao-real',
        'explanation/validacao-fase-12',
        'explanation/aceite-providers',
        'explanation/gates',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Operação',
      collapsed: false,
      items: ['runbook'],
    },
    {
      type: 'category',
      label: '📚 Vocabulário',
      collapsed: false,
      items: ['glossary'],
    },
    {
      type: 'category',
      label: '🤝 Contribuir',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Como contribuir',
          href: 'https://github.com/daneiel/brabo/blob/dev/CONTRIBUTING.md',
        },
        {
          type: 'link',
          label: 'Onde pedir ajuda',
          href: 'https://github.com/daneiel/brabo/blob/dev/SUPPORT.md',
        },
        {
          type: 'link',
          label: 'Reportar vulnerabilidade',
          href: 'https://github.com/daneiel/brabo/blob/dev/SECURITY.md',
        },
      ],
    },
  ],
};

export default sidebars;
