import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEmail, IsOptional, IsString, MaxLength } from 'class-validator';
import { COMPRIMENTO_MAXIMO } from '../../../../domain/auth/password-policy';

/**
 * O que o instalador manda para criar a primeira conta (RN-546, ADR 0155).
 *
 * A senha NÃO tem `@MinLength` aqui, e a ausência é deliberada: a recusa
 * mínima é a do domínio (`exigirSenhaValida`), chamada pelo caso de uso, e
 * escrever o número de novo na camada HTTP criaria uma segunda régua que
 * divergiria da primeira — exatamente o que o ponto 3 do ADR recusa. O
 * `@MaxLength` fica porque não é política: é proteção de argon2id, que copia
 * a entrada antes de derivar, e ela vale ANTES de o corpo chegar ao domínio.
 */
export class FirstAccountInternalDto {
  @ApiProperty({
    example: 'voce@exemplo.dev',
    description:
      'The owner e-mail, typed at the TTY. Normalized before anything is ' +
      'written; it is what the installer records in its marker, since an ' +
      'e-mail identifies and is not a secret.',
  })
  @IsEmail()
  email!: string;

  @ApiProperty({
    example: 'uma frase longa e minha',
    description:
      'Read without echo and confirmed by the installer. Used and discarded ' +
      '— never written to the `.env`, to the marker or to a log, and never ' +
      'generated by any code: there is no path where an account is born with ' +
      'a password the script chose. The minimum is the DOMAIN policy, the ' +
      'same code registration uses; the max length here is argon2id ' +
      'protection, not policy.',
  })
  @IsString()
  @MaxLength(COMPRIMENTO_MAXIMO)
  senha!: string;

  @ApiPropertyOptional({
    example: 'Fulana de Tal',
    description:
      "Display name. Omitted: the personal workspace's name falls back to " +
      'the e-mail local-part (RN-410) — nothing is invented.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  nome?: string;
}
